### ISSUE TITLE
No PyPi Package

### ISSUE THREAD

**Issue by BJamin99** [greatscottgadgets/cynthion#120]
Getting Started says to install the cynthion package using:

`pip install cynthion`

But it appears the package has been yanked so this does not work.

Are there prebuilt packages?

**Comment by martinling** [comment]
The `cynthion` package hasn't been released yet. There will be a 1.0.0 release out soon, please bear with us.

**Comment by martinling** [comment]
There's now an initial 0.1.0 release on PyPI, so you can `pip install cynthion` now.

For more info, see the documentation here:
https://cynthion.readthedocs.io/en/latest/getting_started.html
