### ISSUE TITLE
Flash UID Zeros After --force-offline

### ISSUE THREAD

**Issue by BJamin99** [greatscottgadgets/cynthion#125]
After running `cynthion info --force-offline` the Flash UID shows up only as 0's.  Performing a reset and running `cynthion info` the Flash ID is displayed correctly again.

Hardware: Cynthion r1.4
Firmware version: v1.0.6
USB API version: 1.1
PyPi cynthion version: 0.1.0

Workaround: To reliably find your Cynthion's flash UID, use `apollo flash-info`.

**Comment by mossmann** [comment]
This is caused directly by https://github.com/greatscottgadgets/apollo/issues/102 because `cynthion info` wraps the `apollo info` function.
