### ISSUE TITLE
Support Facedancer on Windows

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/cynthion#170]
Warning! Facedancer does not currently work on Windows. Attempts to use Facedancer with Cynthion on Windows [may cause USB analysis to stop working](https://github.com/greatscottgadgets/cynthion/issues/169)

There are several things that need to happen to bring Facedancer support to Windows:

```[tasklist]
- [ ] #173
- [ ] https://github.com/greatscottgadgets/facedancer/pull/105
- [x] https://github.com/greatscottgadgets/facedancer/pull/104
- [ ] #175
- [ ] https://github.com/greatscottgadgets/libgreat/pull/43
- [x] Reverse #173
- [x] Reverse https://github.com/greatscottgadgets/facedancer/pull/105
- [ ] #169
```

Once these things are done, we'll be able to test and find out if there are additional problems. There may be other bugs in Cynthion, Facedancer, or pygreat that affect only Windows.

**Comment by pickeditmate** [comment]
Ohhhhhhhh, that explains my predicament then, thought it was because I had previously installed facedancer for greatfet. Was just following readthedocs instructions before defcon and hit exactly this issue. 
Fwiw announcement in discord might be needed too.

**Comment by antoinevg** [comment]
GreatFET-related tasks moved to: https://github.com/greatscottgadgets/greatfet/issues/439
