### ISSUE TITLE
Cynthion: Feature request for SoC to provide generic JTAG debugging via PMOD

### ISSUE THREAD

**Issue by nekrondev** [greatscottgadgets/cynthion#69]
Once Cynthion will be released to the public I guess many folks like to tinker with Facedancer CLI and Moondancer firmware. However the current Moondancer firmware uses the PMOD connectors together with Ladybug library to give some insights using a logic analyzer for debugging USB communications.

As found [here](https://tomverbeure.github.io/2021/07/18/VexRiscv-OpenOCD-and-Traps.html) there is a FPGA generic way to add JTAG TAP into softcores for debugging the Moondancer firmware directly on the core. 

Are there any plans to add this option to Cynthion's SoC?

**Comment by antoinevg** [comment]
Fully supported and documented as of: https://github.com/greatscottgadgets/cynthion/pull/76
